"""Byte-for-byte validation of BIP 324 ECDH against libsecp256k1's
reference vectors.

These vectors were generated by an independent implementation and
cross-verified against the BIP 324 paper authors' decoding code; they
are the canonical test data for ``secp256k1_ellswift_xdh`` with the
BIP 324 hash function.  Source:

    bitcoin-core/src/secp256k1/src/modules/ellswift/tests_impl.h:156-164
    (struct ellswift_xdh_test ellswift_xdh_tests_bip324[])

Same 7-vector table that camlcoin's BIP 324 wiring (commit 559c3d1)
validates its ctypes bindings against.

A pass here means ouroboros's V2 handshake, when given matching
inputs, produces the same 32-byte shared secret as Bitcoin Core's
reference libsecp256k1.  This is the prerequisite for v2 interop with
Core — without it, the cipher's ECDH is a self-consistent toy.

NOTE on scope: passing these vectors does NOT yet imply full BIP 324
wire-format interop with Core.  The session-key expansion,
length-cipher derivation, and garbage-terminator schedule are still
the simplified one-key-per-direction layout from the original
``transport_v2`` cipher.  That's tracked as the next NEEDS-INFRA
upgrade; this test pins the ECDH layer so it never regresses.
"""

from __future__ import annotations

import pytest

from ouroboros.transport_v2 import (
    V2Handshake,
    secp256k1_ellswift_create,
    secp256k1_ellswift_xdh,
)


# Each vector matches one row of ``ellswift_xdh_tests_bip324``:
#   priv_ours         - 32-byte secret key for "us"
#   ellswift_ours     - 64-byte ElligatorSwift pubkey we sent
#   ellswift_theirs   - 64-byte ElligatorSwift pubkey peer sent
#   initiating        - True if we are the initiator (party=0 in libsecp256k1)
#   shared_secret     - expected 32-byte BIP 324 shared secret
BIP324_XDH_VECTORS: list[dict[str, object]] = [
    {
        "priv_ours":     "61062ea5071d800bbfd59e2e8b53d47d194b095ae5a4df04936b49772ef0d4d7",
        "ellswift_ours": ("ec0adff257bbfe500c188c80b4fdd640f6b45a482bbc15fc7cef5931deff0aa1"
                          "86f6eb9bba7b85dc4dcc28b28722de1e3d9108b985e2967045668f66098e475b"),
        "ellswift_theirs": ("a4a94dfce69b4a2a0a099313d10f9f7e7d649d60501c9e1d274c300e0d89aafa"
                            "ffffffffffffffffffffffffffffffffffffffffffffffffffffffff8faf88d5"),
        "initiating":    True,
        "shared_secret": "c6992a117f5edbea70c3f511d32d26b9798be4b81a62eaee1a5acaa8459a3592",
    },
    {
        "priv_ours":     "1f9c581b35231838f0f17cf0c979835baccb7f3abbbb96ffcc318ab71e6e126f",
        "ellswift_ours": ("a1855e10e94e00baa23041d916e259f7044e491da6171269694763f018c7e636"
                          "93d29575dcb464ac816baa1be353ba12e3876cba7628bd0bd8e755e721eb0140"),
        "ellswift_theirs": ("fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f"
                            "0000000000000000000000000000000000000000000000000000000000000000"),
        "initiating":    False,
        "shared_secret": "a0138f564f74d0ad70bc337dacc9d0bf1d2349364caf1188a1e6e8ddb3b7b184",
    },
    {
        "priv_ours":     "0286c41cd30913db0fdff7a64ebda5c8e3e7cef10f2aebc00a7650443cf4c60d",
        "ellswift_ours": ("d1ee8a93a01130cbf299249a258f94feb5f469e7d0f2f28f69ee5e9aa8f9b54a"
                          "60f2c3ff2d023634ec7f4127a96cc11662e402894cf1f694fb9a7eaa5f1d9244"),
        "ellswift_theirs": ("ffffffffffffffffffffffffffffffffffffffffffffffffffffffff22d5e441"
                            "524d571a52b3def126189d3f416890a99d4da6ede2b0cde1760ce2c3f98457ae"),
        "initiating":    True,
        "shared_secret": "250b93570d411149105ab8cb0bc5079914906306368c23e9d77c2a33265b994c",
    },
    {
        "priv_ours":     "6c77432d1fda31e9f942f8af44607e10f3ad38a65f8a4bddae823e5eff90dc38",
        "ellswift_ours": ("d2685070c1e6376e633e825296634fd461fa9e5bdf2109bcebd735e5a91f3e58"
                          "7c5cb782abb797fbf6bb5074fd1542a474f2a45b673763ec2db7fb99b737bbb9"),
        "ellswift_theirs": ("56bd0c06f10352c3a1a9f4b4c92f6fa2b26df124b57878353c1fc691c51abea7"
                            "7c8817daeeb9fa546b77c8daf79d89b22b0e1b87574ece42371f00237aa9d83a"),
        "initiating":    False,
        "shared_secret": "1918b741ef5f9d1d7670b050c152b4a4ead2c31be9aecb0681c0cd4324150853",
    },
    {
        "priv_ours":     "a6ec25127ca1aa4cf16b20084ba1e6516baae4d32422288e9b36d8bddd2de35a",
        "ellswift_ours": ("ffffffffffffffffffffffffffffffffffffffffffffffffffffffff053d7ecc"
                          "a53e33e185a8b9be4e7699a97c6ff4c795522e5918ab7cd6b6884f67e683f3dc"),
        "ellswift_theirs": ("ffffffffffffffffffffffffffffffffffffffffffffffffffffffffa7730be3"
                            "0000000000000000000000000000000000000000000000000000000000000000"),
        "initiating":    True,
        "shared_secret": "dd210aa6629f20bb328e5d89daa6eb2ac3d1c658a725536ff154f31b536c23b2",
    },
    {
        "priv_ours":     "0af952659ed76f80f585966b95ab6e6fd68654672827878684c8b547b1b94f5a",
        "ellswift_ours": ("ffffffffffffffffffffffffffffffffffffffffffffffffffffffffc81017fd"
                          "92fd31637c26c906b42092e11cc0d3afae8d9019d2578af22735ce7bc469c72d"),
        "ellswift_theirs": ("9652d78baefc028cd37a6a92625b8b8f85fde1e4c944ad3f20e198bef8c02f19"
                            "fffffffffffffffffffffffffffffffffffffffffffffffffffffffff2e91870"),
        "initiating":    False,
        "shared_secret": "3568f2aea2e14ef4ee4a3c2a8b8d31bc5e3187ba86db10739b4ff8ec92ff6655",
    },
    {
        "priv_ours":     "f90e080c64b05824c5a24b2501d5aeaf08af3872ee860aa80bdcd430f7b63494",
        "ellswift_ours": ("ffffffffffffffffffffffffffffffffffffffffffffffffffffffff11517376"
                          "5dc202cf029ad3f15479735d57697af12b0131dd21430d5772e4ef11474d58b9"),
        "ellswift_theirs": ("12a50f3fafea7c1eeada4cf8d33777704b77361453afc83bda91eef349ae044d"
                            "20126c6200547ea5a6911776c05dee2a7f1a9ba7dfbabbbd273c3ef29ef46e46"),
        "initiating":    True,
        "shared_secret": "e25461fb0e4c162e18123ecde88342d54d449631e9b75a266fd9260c2bb2f41d",
    },
]


# Sanity: every vector must be the right shape.
@pytest.mark.parametrize("vec", BIP324_XDH_VECTORS, ids=lambda v: v["shared_secret"][:16])
def test_vector_shape(vec: dict[str, object]) -> None:
    assert len(bytes.fromhex(vec["priv_ours"])) == 32
    assert len(bytes.fromhex(vec["ellswift_ours"])) == 64
    assert len(bytes.fromhex(vec["ellswift_theirs"])) == 64
    assert len(bytes.fromhex(vec["shared_secret"])) == 32


# The actual byte-for-byte check: 7/7 must agree with libsecp256k1.
@pytest.mark.parametrize(
    "vec_index",
    range(len(BIP324_XDH_VECTORS)),
    ids=[f"vec{i}" for i in range(len(BIP324_XDH_VECTORS))],
)
def test_ellswift_xdh_matches_libsecp256k1_reference(vec_index: int) -> None:
    """Each vector: feed our ``secp256k1_ellswift_xdh`` wrapper the same
    inputs libsecp256k1 uses internally; the output must match
    bit-for-bit.  This is the test camlcoin's wiring uses to lock down
    its own ctypes binding — see camlcoin/lib/schnorr_stubs.c (commit
    559c3d1) for the C-side analog."""
    vec = BIP324_XDH_VECTORS[vec_index]
    priv = bytes.fromhex(vec["priv_ours"])
    ours = bytes.fromhex(vec["ellswift_ours"])
    theirs = bytes.fromhex(vec["ellswift_theirs"])
    initiating = vec["initiating"]
    expected = bytes.fromhex(vec["shared_secret"])

    got = secp256k1_ellswift_xdh(ours, theirs, priv, initiating)
    assert got == expected, (
        f"BIP 324 XDH vector {vec_index} mismatch: "
        f"got={got.hex()} expected={expected.hex()}"
    )


def test_ellswift_xdh_all_seven_vectors_pass() -> None:
    """Aggregate counter for the report: how many of the 7 reference
    vectors pass byte-for-byte."""
    passed = 0
    for vec in BIP324_XDH_VECTORS:
        priv = bytes.fromhex(vec["priv_ours"])
        ours = bytes.fromhex(vec["ellswift_ours"])
        theirs = bytes.fromhex(vec["ellswift_theirs"])
        initiating = vec["initiating"]
        expected = bytes.fromhex(vec["shared_secret"])
        got = secp256k1_ellswift_xdh(ours, theirs, priv, initiating)
        if got == expected:
            passed += 1
    assert passed == len(BIP324_XDH_VECTORS), (
        f"Only {passed}/{len(BIP324_XDH_VECTORS)} BIP 324 vectors passed"
    )


def test_ellswift_create_then_xdh_self_pair() -> None:
    """End-to-end check using the full ``secp256k1_ellswift_create`` /
    ``secp256k1_ellswift_xdh`` round-trip rather than canned encodings:
    if both sides each generate a real keypair, exchange ellswift
    pubkeys, and run the XDH hash with party=0/1 — they must arrive at
    the same shared secret.  This is the actual code path the v2
    handshake takes."""
    import os
    init_priv = os.urandom(32)
    resp_priv = os.urandom(32)
    init_aux = os.urandom(32)
    resp_aux = os.urandom(32)

    init_pub = secp256k1_ellswift_create(init_priv, init_aux)
    resp_pub = secp256k1_ellswift_create(resp_priv, resp_aux)
    assert len(init_pub) == 64
    assert len(resp_pub) == 64

    init_secret = secp256k1_ellswift_xdh(
        ell_ours=init_pub, ell_theirs=resp_pub,
        secret_key=init_priv, initiating=True,
    )
    resp_secret = secp256k1_ellswift_xdh(
        ell_ours=resp_pub, ell_theirs=init_pub,
        secret_key=resp_priv, initiating=False,
    )
    assert init_secret == resp_secret, (
        "ECDH symmetry failure: initiator and responder derived "
        "different secrets from a fresh ellswift keypair"
    )
    assert len(init_secret) == 32


def test_v2handshake_uses_real_ecdh() -> None:
    """``V2Handshake`` should now drive the real ellswift+xdh path, so
    its ``_shared_secret`` agrees between initiator and responder for
    a fresh self-pair.  (Was previously a sorted-key hash —
    self-consistent but not real ECDH.)"""
    initiator = V2Handshake(initiator=True)
    responder = V2Handshake(initiator=False)
    initiator.receive_remote_pubkey(responder.local_pubkey_bytes)
    responder.receive_remote_pubkey(initiator.local_pubkey_bytes)
    assert initiator._shared_secret is not None
    assert initiator._shared_secret == responder._shared_secret
    assert len(initiator._shared_secret) == 32

    # And the local pubkeys must be 64 bytes each (real ellswift output,
    # not a hash concatenation).
    assert len(initiator.local_pubkey_bytes) == 64
    assert len(responder.local_pubkey_bytes) == 64
    # Two fresh handshakes must produce different ephemeral pubkeys.
    other = V2Handshake(initiator=True)
    assert other.local_pubkey_bytes != initiator.local_pubkey_bytes
