"""BIP 324 packet-format test vectors from Bitcoin Core.

These are the exact 7 test vectors run by Core's
``bip324_tests.cpp::packet_test_vectors`` (BOOST_AUTO_TEST_CASE).  Each
vector specifies inputs (private key, both ellswift pubkeys, contents,
AAD, decoy flag, packet index) and expected outputs (session ID,
both-direction garbage terminators, ciphertext or its tail).

Source: bitcoin-core/src/test/bip324_tests.cpp::packet_test_vectors
(commit 32e1f0a, present in this checkout at
``/home/work/hashhog/bitcoin-core``).  The vectors use mainnet network
magic (``SelectParams(MAIN)`` at bip324_tests.cpp:169) so the HKDF salt
is ``b'bitcoin_v2_shared_secret\\xf9\\xbe\\xb4\\xd9'``.

We load the raw vector strings from a JSON fixture
(``tests/fixtures/bip324_packet_test_vectors.json``) generated by a
small extractor that parses ``bip324_tests.cpp`` directly — this avoids
the multi-kilobyte string-literal hand-copy that would otherwise be
error-prone (see the "in_aad" field of vector 2, which is 4095 hex bytes).

Two passing modes are checked per vector:

1. **Forward (encrypt + assert ciphertext)**:
   - Build a cipher from (priv, ellswift_ours, ellswift_theirs).
   - Seek by encrypting ``in_idx`` decoy packets.
   - Encrypt ``in_contents * in_multiply`` with ``in_aad`` and
     ``in_ignore``.
   - Assert ciphertext matches ``out_ciphertext`` (full match) or
     ``out_ciphertext_endswith`` (tail match for long packets).
   - Assert ``session_id``, ``send_garbage_terminator``, and
     ``recv_garbage_terminator`` match the ``mid_*`` fields.

2. **Self-decrypt round-trip**:
   - Build a second cipher with ``self_decrypt=True`` (swapped
     send/recv P keys; see bip324.cpp:Initialize).
   - Seek to the same packet index, then decrypt the ciphertext from
     step 1 and assert the recovered contents and IGNORE bit match.

Together these cover the full BIP 324 key schedule (HKDF salt + label
set), length cipher (FSChaCha20), contents AEAD (FSChaCha20Poly1305
with periodic rekey), packet header byte placement, AAD binding,
session id, and per-direction garbage terminators.

Out of scope: Core's bit-flip / wrong-side / aad-mutation reject cases
at error=1..12 in TestBIP324PacketVector — those verify Core-specific
reject behaviour, not the wire format.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from ouroboros.transport_v2 import (
    BIP324Cipher,
    secp256k1_ellswift_xdh,
)


_FIXTURE_PATH = (
    Path(__file__).parent / "fixtures" / "bip324_packet_test_vectors.json"
)


def _load_vectors() -> list[dict[str, object]]:
    with _FIXTURE_PATH.open() as f:
        return json.load(f)


PACKET_TEST_VECTORS: list[dict[str, object]] = _load_vectors()


# --- vector runner --------------------------------------------------------


def _run_vector(vec: dict[str, object]) -> dict[str, object]:
    """Drive one test vector through the cipher.  Returns a dict of
    actual values for assertion.

    Mirrors bitcoin-core/src/test/bip324_tests.cpp:25-159
    (TestBIP324PacketVector) but only the no-error ``error == 0`` case
    plus the self-decrypt round-trip.
    """
    in_priv = bytes.fromhex(vec["in_priv_ours"])
    in_ours = bytes.fromhex(vec["in_ellswift_ours"])
    in_theirs = bytes.fromhex(vec["in_ellswift_theirs"])
    in_initiating: bool = vec["in_initiating"]
    in_contents = bytes.fromhex(vec["in_contents"])
    in_multiply: int = vec["in_multiply"]
    in_aad = bytes.fromhex(vec["in_aad"])
    in_ignore: bool = vec["in_ignore"]
    in_idx: int = vec["in_idx"]

    # ECDH first.  Same path as test_bip324_vectors.py, but with the
    # packet vectors' inputs.
    ecdh = secp256k1_ellswift_xdh(in_ours, in_theirs, in_priv, in_initiating)

    # Forward cipher: encrypt and assert ciphertext + session metadata.
    enc = BIP324Cipher.from_secrets(
        ecdh, initiator=in_initiating, network="mainnet"
    )

    # Seek by encrypting in_idx empty IGNORE packets.  We capture each
    # one to feed through the self-decrypt cipher below, mirroring
    # ``dummies[in_idx]`` in TestBIP324PacketVector.
    dummies: list[bytes] = []
    for _ in range(in_idx):
        dummies.append(enc.encrypt_packet(b"", aad=b"", ignore=True))

    contents = in_contents * in_multiply
    ciphertext = enc.encrypt_packet(contents, aad=in_aad, ignore=in_ignore)

    # Self-decrypt round-trip.  Build a second cipher with
    # self_decrypt=True so the same side that encrypted can also
    # decrypt without knowing the peer's private key.
    dec = BIP324Cipher.from_secrets(
        ecdh, initiator=in_initiating, network="mainnet", self_decrypt=True
    )
    for dummy_ct in dummies:
        contents_len = dec.decrypt_length(dummy_ct[:3])
        assert contents_len == 0, "dummy packet had non-zero contents length"
        result = dec.decrypt_contents(dummy_ct[3:], 0, aad=b"")
        assert result is not None, "dummy packet auth failed during seek"

    contents_len = dec.decrypt_length(ciphertext[:3])
    assert contents_len == len(contents), (
        f"decrypted length {contents_len} != contents {len(contents)}"
    )
    result = dec.decrypt_contents(ciphertext[3:], contents_len, aad=in_aad)
    assert result is not None, "real packet auth failed"
    decrypted, was_decoy = result

    return {
        "ciphertext": ciphertext.hex(),
        "session_id": enc.session_id.hex(),
        "send_garbage_terminator": enc.send_garbage_terminator.hex(),
        "recv_garbage_terminator": enc.recv_garbage_terminator.hex(),
        "decrypted_contents": decrypted.hex(),
        "decrypted_was_decoy": was_decoy,
    }


# --- shape sanity ---------------------------------------------------------


def test_seven_vectors_loaded() -> None:
    assert len(PACKET_TEST_VECTORS) == 7, (
        f"expected 7 packet test vectors, got {len(PACKET_TEST_VECTORS)}"
    )


@pytest.mark.parametrize(
    "vec",
    PACKET_TEST_VECTORS,
    ids=[f"vec{i}_idx={v['in_idx']}" for i, v in enumerate(PACKET_TEST_VECTORS)],
)
def test_packet_vector_shape(vec: dict[str, object]) -> None:
    assert len(bytes.fromhex(vec["in_priv_ours"])) == 32
    assert len(bytes.fromhex(vec["in_ellswift_ours"])) == 64
    assert len(bytes.fromhex(vec["in_ellswift_theirs"])) == 64
    assert len(bytes.fromhex(vec["mid_send_garbage_terminator"])) == 16
    assert len(bytes.fromhex(vec["mid_recv_garbage_terminator"])) == 16
    assert len(bytes.fromhex(vec["out_session_id"])) == 32


# --- byte-for-byte mid-state assertions ----------------------------------


@pytest.mark.parametrize(
    "vec_index",
    range(7),
    ids=[f"vec{i}" for i in range(7)],
)
def test_packet_vector_session_metadata(vec_index: int) -> None:
    """Session id + both garbage terminators must match Core's expected
    values bit-for-bit.  Locks down the HKDF salt + label set."""
    vec = PACKET_TEST_VECTORS[vec_index]
    actual = _run_vector(vec)
    assert actual["session_id"] == vec["out_session_id"], (
        f"vec{vec_index}: session_id mismatch"
    )
    assert (
        actual["send_garbage_terminator"]
        == vec["mid_send_garbage_terminator"]
    ), f"vec{vec_index}: send_garbage_terminator mismatch"
    assert (
        actual["recv_garbage_terminator"]
        == vec["mid_recv_garbage_terminator"]
    ), f"vec{vec_index}: recv_garbage_terminator mismatch"


# --- byte-for-byte ciphertext assertions ---------------------------------


@pytest.mark.parametrize(
    "vec_index",
    range(7),
    ids=[f"vec{i}" for i in range(7)],
)
def test_packet_vector_ciphertext(vec_index: int) -> None:
    """Encrypted packet must match Core's published ciphertext.  Locks
    down length cipher (FSChaCha20), contents cipher
    (FSChaCha20Poly1305), header byte placement, AAD binding, and rekey
    schedule simultaneously."""
    vec = PACKET_TEST_VECTORS[vec_index]
    actual = _run_vector(vec)
    if vec["out_ciphertext"]:
        assert actual["ciphertext"] == vec["out_ciphertext"], (
            f"vec{vec_index}: full ciphertext mismatch\n"
            f"  got     ={actual['ciphertext'][:80]}...\n"
            f"  expected={vec['out_ciphertext'][:80]}..."
        )
    else:
        endswith = vec["out_ciphertext_endswith"]
        assert actual["ciphertext"].endswith(endswith), (
            f"vec{vec_index}: ciphertext tail mismatch\n"
            f"  tail got     ={actual['ciphertext'][-len(endswith):][:80]}...\n"
            f"  tail expected={endswith[:80]}..."
        )


# --- self-decrypt round-trip ---------------------------------------------


@pytest.mark.parametrize(
    "vec_index",
    range(7),
    ids=[f"vec{i}" for i in range(7)],
)
def test_packet_vector_self_decrypt(vec_index: int) -> None:
    """After encrypting through the forward cipher, a self-decrypting
    twin must recover the original contents and IGNORE bit."""
    vec = PACKET_TEST_VECTORS[vec_index]
    actual = _run_vector(vec)
    expected_contents = (
        bytes.fromhex(vec["in_contents"]) * vec["in_multiply"]
    ).hex()
    assert actual["decrypted_contents"] == expected_contents, (
        f"vec{vec_index}: decrypted contents mismatch"
    )
    assert actual["decrypted_was_decoy"] == vec["in_ignore"], (
        f"vec{vec_index}: IGNORE bit mismatch (got "
        f"{actual['decrypted_was_decoy']}, expected {vec['in_ignore']})"
    )


# --- aggregate counter ---------------------------------------------------


def test_all_packet_vectors_pass() -> None:
    """Aggregate counter for the report: how many of the 7 published
    BIP 324 packet vectors pass byte-for-byte (mid-state + forward
    ciphertext + self-decrypt)."""
    passed = 0
    failures: list[tuple[int, str]] = []
    for i, vec in enumerate(PACKET_TEST_VECTORS):
        try:
            actual = _run_vector(vec)
            ok = (
                actual["session_id"] == vec["out_session_id"]
                and actual["send_garbage_terminator"]
                    == vec["mid_send_garbage_terminator"]
                and actual["recv_garbage_terminator"]
                    == vec["mid_recv_garbage_terminator"]
            )
            if vec["out_ciphertext"]:
                ok = ok and actual["ciphertext"] == vec["out_ciphertext"]
            else:
                ok = ok and actual["ciphertext"].endswith(
                    vec["out_ciphertext_endswith"]
                )
            # Self-decrypt round-trip must also recover the contents.
            expected_pt = (
                bytes.fromhex(vec["in_contents"]) * vec["in_multiply"]
            ).hex()
            ok = (
                ok
                and actual["decrypted_contents"] == expected_pt
                and actual["decrypted_was_decoy"] == vec["in_ignore"]
            )
            if ok:
                passed += 1
            else:
                failures.append((i, "mid/out mismatch"))
        except Exception as e:
            failures.append((i, repr(e)))
    assert passed == len(PACKET_TEST_VECTORS), (
        f"Only {passed}/{len(PACKET_TEST_VECTORS)} BIP 324 packet vectors "
        f"passed byte-for-byte. Failures: {failures}"
    )
